FROM quay.io/jupyter/minimal-notebook:latest
LABEL authors="sergeygurvich"

# Install dependencies
RUN pip install matplotlib pandas transformers torch torchvision torchaudio

# Clone git repo
RUN git clone https://github.com/Dr-Nathan-Fox/EcoViz_CLIP

# Run JupyterLab when the container launches
CMD ["jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--no-browser"]
