# Use an official Jupyter image as a parent image
# More info: https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html
FROM quay.io/jupyter/minimal-notebook:latest

LABEL authors="sergeygurvich"

# Run JupyterLab when the container launches
CMD ["jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--no-browser"]
